### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by fatinghenji** [MeetWq/nonebot-plugin-hikarisearch#1]
- 使用`/搜图`报错如下：
```python
05-17 18:00:14 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_hikarisearch, type=message, priority=13, temp=False> failed.                                                                    
Traceback (most recent call last):                                                                                                                                                                            
  File "/usr/local/bin/nb", line 8, in <module>                                                                                                                                                               
    sys.exit(main())                                                                                                                                                                                          
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__                                                                                                                         
    return self.main(*args, **kwargs)                                                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main                                                                                                                             
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_hikarisearch/__init__.py", line 90, in handler
    await send_msg(
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_hikarisearch/__init__.py", line 120, in send_msg
   await send_forward_msg(bot, event, "HikariSearch", bot.self_id, msgs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_hikarisearch/__init__.py", line 138, in send_forward_msg
    await bot.call_api(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/onebot/v11/adapter.py", line 140, in _call_api
    raise NetworkError(
nonebot.adapters.onebot.v11.exception.NetworkError: <NetWorkError message=HTTP request received unexpected status code: 404>
```
- 使用`/saucenao搜图`，机器人回复`出错了，请稍后再试`，同时控制台报错如下：
```python
05-17 18:02:12 [WARNING] nonebot_plugin_hikarisearch | Traceback (most recent call last):  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_hikarisearch/__init__.py", line 83, in handler
    res = await source.func(img)
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_hikarisearch/data_source.py", line 13, in search_saucenao
    result = await post("/api/SauceNAO", data, image)
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_hikarisearch/data_source.py", line 85, in post
    return resp.json()
  File "/usr/local/lib/python3.8/dist-packages/httpx/_models.py", line 1517, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
- 使用`/iqdb搜图`，报错如下：
```python
05-17 18:03:55 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_hikarisearch, type=message, priority=13, temp=False> failed.                                                                    
Traceback (most recent call last):                                                                                                                                                                            
  File "/usr/local/bin/nb", line 8, in <module>                                                                                                                                                               
    sys.exit(main())                                                                                                                                                                                          
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__                                                                                                                         
    return self.main(*args, **kwargs)                                                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main                                                                                                                             
    rv = self.invoke(ctx)                                                                                                                                                                                     
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_hikarisearch/__init__.py", line 90, in handler
    await send_msg(
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_hikarisearch/__init__.py", line 120, in send_msg
    await send_forward_msg(bot, event, "HikariSearch", bot.self_id, msgs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_hikarisearch/__init__.py", line 138, in send_forward_msg
    await bot.call_api(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/onebot/v11/adapter.py", line 140, in _call_api
    raise NetworkError(
nonebot.adapters.onebot.v11.exception.NetworkError: <NetWorkError message=HTTP request received unexpected status code: 404>
```
-

**Comment by MeetWq** [comment]
这个插件默认是调用 [HikariSearch](https://github.com/mixmoe/HikariSearch) 的 [演示站点](https://hikari.obfs.dev/) 来搜索的
可能用的人多了会不太稳定
可以考虑自己部署一个站点，然后修改默认的 `hikarisearch_api`
部署过程看 HikariSearch 的仓库 [部署到 Cloudflare](https://github.com/mixmoe/HikariSearch#%E9%83%A8%E7%BD%B2%E5%88%B0-cloudflare)
